import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { useSelector } from 'react-redux';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { RootState } from '../store';
import { generateReportSummary } from '../services/geminiService';
import { useAppTheme } from '../hooks/useAppTheme';
import { ThreeDCard } from '../components/ThreeDCard';

const ReportScreen = () => {
    const theme = useAppTheme();
    const user = useSelector((state: RootState) => state.auth.user);
    const healthData = useSelector((state: RootState) => state.health.healthData[user?.id || '']);

    const [reportText, setReportText] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const handleGenerateReport = async () => {
        if (!healthData || healthData.length === 0) {
            Alert.alert('No Data', 'No health data available to generate report.');
            return;
        }

        setIsLoading(true);
        const summary = await generateReportSummary(healthData.slice(-30));
        setReportText(summary);
        setIsLoading(false);
    };

    const handleDownloadPDF = async () => {
        if (!reportText) return;

        const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: Helvetica, sans-serif; padding: 20px; }
            h1 { color: #333; }
            .header { margin-bottom: 20px; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
            .content { line-height: 1.6; color: #555; }
            .footer { margin-top: 30px; font-size: 12px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Health Report for ${user?.name}</h1>
            <p>Date: ${new Date().toLocaleDateString()}</p>
          </div>
          <div class="content">
            <h2>Summary Analysis</h2>
            <p>${reportText.replace(/\n/g, '<br/>')}</p>
          </div>
          <div class="footer">
            Generated by VoidEscapers Health App
          </div>
        </body>
      </html>
    `;

        try {
            const { uri } = await Print.printToFileAsync({ html: htmlContent });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (error) {
            Alert.alert('Error', 'Could not generate PDF');
            console.error(error);
        }
    };

    return (
        <ScrollView style={[styles.container, { backgroundColor: theme.background }]}>
            <ThreeDCard style={styles.card}>
                <Text style={[styles.title, { color: theme.text }]}>Monthly Health Report</Text>
                <Text style={[styles.description, { color: theme.secondary }]}>
                    Generate a comprehensive analysis of your health data powered by Gemini AI.
                </Text>

                <TouchableOpacity
                    style={[styles.button, { backgroundColor: theme.primary }]}
                    onPress={handleGenerateReport}
                    disabled={isLoading}
                >
                    {isLoading ? (
                        <ActivityIndicator color="#FFF" />
                    ) : (
                        <Text style={styles.buttonText}>Generate Analysis</Text>
                    )}
                </TouchableOpacity>
            </ThreeDCard>

            {reportText ? (
                <ThreeDCard style={styles.resultCard}>
                    <Text style={[styles.resultTitle, { color: theme.text }]}>Analysis Result</Text>
                    <Text style={[styles.resultText, { color: theme.text }]}>{reportText}</Text>

                    <TouchableOpacity style={[styles.downloadButton, { borderColor: theme.primary }]} onPress={handleDownloadPDF}>
                        <Text style={[styles.downloadText, { color: theme.primary }]}>Download PDF</Text>
                    </TouchableOpacity>
                </ThreeDCard>
            ) : null}
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
    },
    card: {
        padding: 20,
        marginBottom: 20,
        alignItems: 'center',
    },
    title: {
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    description: {
        textAlign: 'center',
        marginBottom: 20,
    },
    button: {
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 25,
        minWidth: 200,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    resultCard: {
        padding: 20,
        marginBottom: 40,
    },
    resultTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    resultText: {
        fontSize: 14,
        lineHeight: 22,
        marginBottom: 20,
    },
    downloadButton: {
        borderWidth: 1,
        padding: 12,
        borderRadius: 10,
        alignItems: 'center',
    },
    downloadText: {
        fontWeight: 'bold',
    },
});

export default ReportScreen;
